version: '3.9'

services:
  postgres:
    image: postgis/postgis:14-3.5-alpine
    container_name: springBoardApp_postgres
    hostname: springBoardApp_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME:-springboard}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
    networks:
      springBoardApp_network:


networks:
  springBoardApp_network:
    name: 'springBoardApp_network'
